NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/localhost-9050-ca-org3-example-com.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/localhost-9050-ca-org3-example-com.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/localhost-9050-ca-org3-example-com.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/localhost-9050-ca-org3-example-com.pem
        OrganizationalUnitIdentifier: orderer
